### ISSUE TITLE
How to authenticate for "formio-app-servicetracker"?

### ISSUE THREAD

**Issue by JenifferWuUCLA** [formio/formio-app-servicetracker#2]
When I executed the command "formio bootstrap formio/formio-app-servicetracker", I encountered the Authentication prompt.
    So, would you pls tell me what is the email and password?

**Comment by travist** [comment]
This is your Form.io account credentials. Just create an account @ https://form.io (its free) and then when you run the bootstrap, you will see that project show up in your account.

Thanks!

Travis.

**Comment by JenifferWuUCLA** [comment]
Now, I can start the application after I passed the authentication. But, would pls tell me what is the Email and password in the login form? 
    I tried the account @ https://form.io, but the login failed.

![image](https://cloud.githubusercontent.com/assets/25890017/23246509/360a6ae4-f9cf-11e6-9f99-066011217e84.png)

![image](https://cloud.githubusercontent.com/assets/25890017/23246551/746e6696-f9cf-11e6-8861-74db75c93999.png)

**Comment by travist** [comment]
Each project is its own independent database of users so if you want to log into the application, you will need to create an account within your Project to log into the app. To do this, go to https://form.io, go to the Admin resource, and then click on Preview and then fill out the form to create a new admin account. You can then use that account to log into this app.
